name: Publish to FlakeHub

on:
  push:
    branches:
      - main

jobs:
  flakehub-publish:
    runs-on: [self-hosted, linux, x64]
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/flakehub-push@main
        with:
          name: DeterminateSystems/flakehub-push
          rolling: true
          visibility: public
